import { defineConfig } from 'oxlint';

export default defineConfig({
	plugins: ['node', 'eslint', 'typescript', 'oxc', 'import', 'jsdoc', 'promise', 'unicorn'],
	categories: {
		correctness: 'error',
		suspicious: 'error',
		pedantic: 'error',
		perf: 'error',
		style: 'error',
		restriction: 'error',
		nursery: 'error',
	},
	ignorePatterns: ['**/dist/**', '**/*.d.ts'],
	options: {
		typeAware: true,
	},
	//#region Overrides
	overrides: [
		{
			files: ['**/ts/native.ts'],
			rules: {
				'eslint/max-lines': 'off',
			},
		},
		{
			files: [
				'**/*.test.*',
				'**/test/**/*',
				'**/tests/**/*',
				'**/test-addon/**/*',
				'**/src/**/*', // build helper scripts
				'**/examples/**/*',
				'**/scripts/**/*',
				'**/install.js',
			],
			rules: {
				'eslint/no-console': 'off',
				'eslint/no-magic-numbers': 'off',
				'node/no-sync': 'off',
				'node/no-top-level-await': 'off',
				'typescript/no-floating-promises': 'off',
				'typescript/no-unnecessary-condition': 'off',
			},
		},
		{
			files: ['**/*.test.*', '**/test/**/*', '**/tests/**/*', '**/test-addon/**/*'],
			rules: {
				'eslint/max-lines-per-function': 'off',
				'eslint/max-lines': 'off',
				'eslint/max-statements': 'off',
				'unicorn/no-useless-undefined': 'off',
				'eslint/no-underscore-dangle': 'off',
				'typescript/no-unnecessary-boolean-literal-compare': 'off',
			},
		},
		{
			files: ['**/src/build-*', '**/examples/**/*'],
			rules: {
				'unicorn/no-process-exit': 'off',
			},
		},
		{
			files: ['**/*.js', '**/*.mjs'],
			rules: {
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/prefer-nullish-coalescing': 'off',
				'unicorn/numeric-separators-style': 'off',
			},
		},
	],
	//#endregion Overrides
	rules: {
		//#region Unwanted
		'eslint/capitalized-comments': 'off',
		'eslint/class-methods-use-this': 'off',
		'eslint/id-length': 'off',
		'eslint/no-bitwise': 'off',
		'eslint/no-continue': 'off',
		'eslint/no-duplicate-imports': 'off',
		'eslint/no-implicit-coercion': 'off',
		'eslint/no-inline-comments': 'off',
		'eslint/no-plusplus': 'off',
		'eslint/no-shadow': 'off',
		'eslint/no-ternary': 'off',
		'eslint/no-undef': 'off',
		'eslint/no-undefined': 'off',
		'eslint/no-useless-assignment': 'off',
		'eslint/no-warning-comments': 'off',
		'eslint/one-var': 'off',
		'eslint/prefer-destructuring': 'off',
		'eslint/prefer-named-capture-group': 'off',
		'eslint/sort-imports': 'off',
		'eslint/sort-keys': 'off',
		'eslint/sort-vars': 'off',
		'require-await': 'off',
		'import/exports-last': 'off',
		'import/group-exports': 'off',
		'import/no-anonymous-default-export': 'off',
		'import/no-default-export': 'off',
		'import/no-dynamic-require': 'off',
		'import/no-named-as-default-member': 'off',
		'import/no-named-export': 'off',
		'import/no-namespace': 'off',
		'import/no-nodejs-modules': 'off',
		'import/no-relative-parent-imports': 'off',
		'import/no-unassigned-import': 'off',
		'import/namespace': 'off',
		'import/prefer-default-export': 'off',
		'import/unambiguous': 'off',
		'jsdoc/no-defaults': 'off',
		'jsdoc/require-param-description': 'off',
		'jsdoc/require-param-type': 'off',
		'jsdoc/require-param': 'off',
		'jsdoc/require-property': 'off',
		'jsdoc/require-returns-description': 'off',
		'jsdoc/require-returns': 'off',
		'node/global-require': 'off',
		'oxc/no-async-await': 'off',
		'oxc/no-optional-chaining': 'off',
		'oxc/no-rest-spread-properties': 'off',
		'promise/avoid-new': 'off',
		'promise/prefer-await-to-callbacks': 'off',
		'typescript/class-literal-property-style': 'off',
		'typescript/explicit-function-return-type': 'off',
		'typescript/no-inferrable-types': 'off',
		'typescript/no-unsafe-type-assertion': 'off',
		'typescript/prefer-readonly-parameter-types': 'off',
		'typescript/prefer-return-this-type': 'off',
		'typescript/require-await': 'off',
		'typescript/strict-boolean-expressions': 'off',
		'typescript/unbound-method': 'off',
		'unicorn/explicit-length-check': 'off',
		'unicorn/import-style': 'off',
		'unicorn/no-zero-fractions': 'off',
		'unicorn/no-null': 'off',
		'unicorn/number-literal-case': 'off',
		'unicorn/prefer-number-coercion': 'off',
		'unicorn/prefer-dom-node-append': 'off',
		'unicorn/prefer-event-target': 'off',
		'unicorn/prefer-global-this': 'off',
		//#endregion Unwanted

		//#region Customized
		'eslint/arrow-body-style': ['error', 'as-needed'],
		'eslint/max-lines-per-function': ['error', { max: 100 }],
		'eslint/max-lines': ['error', { max: 600 }],
		'eslint/max-params': ['error', { max: 6 }],
		'eslint/max-statements': ['error', { max: 50 }],
		'eslint/no-magic-numbers': [
			'error',
			{
				ignore: [
					0xffffff, -10, -1, -0.5, 0, 0.05, 0.1, 0.001, 0.5, 1, 2, 3, 4, 5, 8, 10, 15, 16,
					24, 32, 60, 64, 100, 128, 255, 256, 512, 720, 1000, 1024, 1280,
				],
				ignoreDefaultValues: true,
				ignoreClassFieldInitialValues: true,
				ignoreNumericLiteralTypes: true,
				ignoreTypeIndexes: true,
			},
		],
		'eslint/no-underscore-dangle': ['error', { allowAfterThis: true }],
		'promise/param-names': ['error', { resolvePattern: '^res$', rejectPattern: '^rej$' }],
		'typescript/consistent-type-definitions': ['error', 'type'],
		'typescript/prefer-nullish-coalescing': ['error', { ignoreMixedLogicalExpressions: true }],
		'typescript/no-confusing-void-expression': [
			'error',
			{ ignoreVoidReturningFunctions: true, ignoreArrowShorthand: true },
		],
		'typescript/no-floating-promises': ['error', { ignoreIIFE: true }],
		'unicorn/numeric-separators-style': [
			'error',
			{ hexadecimal: { onlyIfContainsSeparator: true } },
		],
		'unicorn/switch-case-braces': ['error', 'avoid'],
		//#endregion Customized
	},
});
