import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

type TTestHelper = (...args: unknown[]) => unknown;
type TBooleanTestHelper = (...args: unknown[]) => boolean;
type TNumberTestHelper = (...args: unknown[]) => number;
type TStringTestHelper = (...args: unknown[]) => string;

type TTestAddon = {
	CrashProbe: new () => { ping: () => number };
	empty: TTestHelper;
	throwing: TTestHelper;
	retUndefined: () => undefined;
	retNull: () => null;
	retStr: () => string;
	retNum: () => number;
	retExt: () => object;
	retExtNonNull: () => object;
	setterExtRoundTrip: TTestHelper;
	retBool: () => boolean;
	retObject: () => object;
	retArray: () => unknown[];
	reqArgs3: (...args: unknown[]) => boolean;
	isArg0Empty: (value?: unknown) => boolean;
	reqStrArg: TStringTestHelper;
	useStrArg: TStringTestHelper;
	letStrArg: TStringTestHelper;
	weakStrArg: TStringTestHelper;
	reqIntArg: TNumberTestHelper;
	useIntArg: TNumberTestHelper;
	letIntArg: TNumberTestHelper;
	weakIntArg: TNumberTestHelper;
	reqUintArg: TNumberTestHelper;
	useUintArg: TNumberTestHelper;
	letUintArg: TNumberTestHelper;
	weakUintArg: TNumberTestHelper;
	reqInt64Arg: TNumberTestHelper;
	useInt64Arg: TNumberTestHelper;
	letInt64Arg: TNumberTestHelper;
	weakInt64Arg: TNumberTestHelper;
	reqUint64Arg: TNumberTestHelper;
	useUint64Arg: TNumberTestHelper;
	letUint64Arg: TNumberTestHelper;
	weakUint64Arg: TNumberTestHelper;
	reqBoolArg: TBooleanTestHelper;
	useBoolArg: TBooleanTestHelper;
	letBoolArg: TBooleanTestHelper;
	softBoolArg: TBooleanTestHelper;
	weakBoolArg: TBooleanTestHelper;
	reqOffsArg: TNumberTestHelper;
	useOffsArg: TNumberTestHelper;
	letOffsArg: TNumberTestHelper;
	weakOffsArg: TNumberTestHelper;
	reqDoubleArg: TNumberTestHelper;
	useDoubleArg: TNumberTestHelper;
	letDoubleArg: TNumberTestHelper;
	weakDoubleArg: TNumberTestHelper;
	reqFloatArg: TNumberTestHelper;
	useFloatArg: TNumberTestHelper;
	letFloatArg: TNumberTestHelper;
	weakFloatArg: TNumberTestHelper;
	reqExtArg: TTestHelper;
	useExtArg: TTestHelper;
	letExtArg: TTestHelper;
	reqObjArg: TTestHelper;
	useObjArg: TTestHelper;
	letObjArg: TTestHelper;
	reqArrayArg: TTestHelper;
	useArrayArg: TTestHelper;
	letArrayArg: TTestHelper;
	letArrayStrArg: TTestHelper;
	reqFunArg: TTestHelper;
	reqArrvArg: TTestHelper;
	reqBufArg: TTestHelper;
	reqTypedArg: TTestHelper;
	strcasestrProbe: () => { haystack: string; needle: string; index: number };
	getArrayDataUint32Meta: TTestHelper;
	getDataPresence: TTestHelper;
	getBufferDataFloatMeta: TTestHelper;
	setBufferDataFloatFirst: TTestHelper;
	consoleLogString: () => void;
	consoleLogArgs: () => void;
	globalLogString: () => void;
	globalLogArgs: () => void;
};

export const test = require('./build/Release/test.node') as TTestAddon;
